# my_train.yaml - Small model for RTX 3050 (4GB VRAM)
# CrystaLLM training - resuming from checkpoint
init_from: resume
# CrystaLLM training from scratch

# Dataset
dataset: mp_oqmd_nomad_cifs_semisymm_Z_props_2

# Output
out_dir: out_crystallm_v1_from_scratch

# Evaluation & Logging
eval_interval: 500
log_interval: 10
eval_iters_train: 50
eval_iters_val: 50
always_save_checkpoint: true
validate: false  # Set to true once val.bin is available

# Model architecture (small model for 4GB GPU)
n_layer: 6
n_head: 6
n_embd: 384
block_size: 512
dropout: 0.1
bias: false

# Training
batch_size: 8
gradient_accumulation_steps: 8  # Effective batch size: 8*8=64
max_iters: 10000
learning_rate: 3e-4
min_lr: 3e-5
warmup_iters: 1000
lr_decay_iters: 50000
decay_lr: true

# Optimizer
weight_decay: 0.1
beta1: 0.9
beta2: 0.95
grad_clip: 1.0

# System
device: cuda
dtype: float16
compile: false  # Disable for compatibility
